### ISSUE TITLE
When attempting to use the 'automate' command, it either cannot be found or fails to execute properly, resulting in an error message. @v0.11, v0.11.1, v0.11.2

### ISSUE THREAD

**Issue by kyeyang** [mwwlean/django_tailwindcss_automated#6]
I'm encountering an issue with the 'automate' command in versions v0.11, v0.11.1, and v0.11.2 of the package. When I attempt to use the 'automate' command, it does not work as expected. Instead, I receive an error message indicating that the command cannot be found or executed.

**Comment by mwwlean** [comment]
### Fixed. Please update to the latest version v0.11.3.

**You can update using the following command:**

`pip install django-tailwindcss-automated==0.11.3`
